// SPOTIFY
// Electron
export const CHECK_IF_LOGGED_IN = 'CHECK_IF_LOGGED_IN';
// Redux
export const FETCH_SPOTIFY_USER_DATA = {
    REQUEST: 'FETCH_SPOTIFY_USER_DATA_REQUEST',
    SUCCESS: 'FETCH_SPOTIFY_USER_DATA_SUCCESS',
    FAILED: 'FETCH_SPOTIFY_USER_DATA_FAILED',
};
