// SPOTIFY
// Electron
export const CHECK_IF_LOGGED_IN = 'CHECK_IF_LOGGED_IN';
// Redux
export const FETCH_SPOTIFY_USER_DATA = {
    REQUEST: 'FETCH_SPOTIFY_USER_DATA_REQUEST',
    SUCCESS: 'FETCH_SPOTIFY_USER_DATA_SUCCESS',
    FAILED: 'FETCH_SPOTIFY_USER_DATA_FAILED',
};

export const SPOTIFY_URL = {
    LOGIN: process.env.REACT_APP_SERVER_ADDRESS + '/spotify/login',
    ACCESS_TOKEN: process.env.REACT_APP_SERVER_ADDRESS + '/spotify/token',
};
