export const ActionTypes = {
    GET_ACCESS_TOKEN: {
        REQUEST: 'GET_ACCESS_TOKEN_REQUEST',
        SUCCESS: 'GET_ACCESS_TOKEN_SUCCESS',
        FAILURE: 'GET_ACCESS_TOKEN_FAILURE',
    },
    GET_USER_DATA: {
        REQUEST: 'GET_USER_DATA_REQUEST',
        SUCCESS: 'GET_USER_DATA_SUCCESS',
        FAILURE: 'GET_USER_DATA_FAILURE',
    },
    SAVE_SPOTIFY: {
        ACCESS_TOKEN: 'SAVE_ACCESS_TOKEN',
        USER_DATA: 'SAVE_USER_DATA',
    },
    RUN_THROUGH_CHECKLIST: 'RUN_THROUGH_CHECKLIST',
    HIDE_ERROR: 'HIDE_ERROR',
};
